swagger: "2.0"
info:
  title: Cake Store API
  description: API for managing cakes, orders, reviews, and users (Final Project Part 3)
  version: "1.0.0"

servers: - url: https://cse-341-node-project3.onrender.com
         - url: http://localhost:3000
tags:
  - name: Cakes
    description: Cake management
  - name: Orders
    description: Customer orders
  - name: Reviews
    description: Cake reviews
  - name: Users
    description: Registered users

paths:
  # --- Cakes ---
  /api/cakes:
    get:
      tags: [Cakes]
      summary: Get all cakes
      responses:
        200:
          description: A list of all cakes
        500:
          description: Server error while fetching cakes
    post:
      tags: [Cakes]
      summary: Create a new cake
      parameters:
        - in: body
          name: cake
          description: Cake to create
          required: true
          schema:
            $ref: "#/definitions/Cake"
      responses:
        201:
          description: Cake created successfully
        400:
          description: Invalid cake data
        500:
          description: Server error while creating cake

  /api/cakes/{id}:
    get:
      tags: [Cakes]
      summary: Get cake by ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Cake found
        404:
          description: Cake not found
        500:
          description: Server error
    put:
      tags: [Cakes]
      summary: Update a cake
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: cake
          required: true
          schema:
            $ref: "#/definitions/Cake"
      responses:
        200:
          description: Cake updated successfully
        400:
          description: Invalid data for update
        404:
          description: Cake not found
        500:
          description: Server error
    delete:
      tags: [Cakes]
      summary: Delete a cake
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        204:
          description: Cake deleted
        404:
          description: Cake not found
        500:
          description: Server error

  # --- Orders ---
  /api/orders:
    get:
      tags: [Orders]
      summary: Get all orders (Protected)
      security:
        - oauth2: []
      responses:
        200:
          description: List of all orders
        401:
          description: Unauthorized
        500:
          description: Server error
    post:
      tags: [Orders]
      summary: Create new order (Protected)
      security:
        - oauth2: []
      parameters:
        - in: body
          name: order
          required: true
          schema:
            $ref: "#/definitions/Order"
      responses:
        201:
          description: Order created
        400:
          description: Invalid order data
        401:
          description: Unauthorized
        500:
          description: Server error

  /api/orders/{id}:
    get:
      tags: [Orders]
      summary: Get order by ID (Protected)
      security:
        - oauth2: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Order found
        401:
          description: Unauthorized
        404:
          description: Order not found
        500:
          description: Server error
    put:
      tags: [Orders]
      summary: Update order (Protected)
      security:
        - oauth2: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: order
          required: true
          schema:
            $ref: "#/definitions/Order"
      responses:
        200:
          description: Order updated
        400:
          description: Invalid data
        401:
          description: Unauthorized
        404:
          description: Order not found
        500:
          description: Server error
    delete:
      tags: [Orders]
      summary: Delete order (Protected)
      security:
        - oauth2: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        204:
          description: Order deleted
        401:
          description: Unauthorized
        404:
          description: Order not found
        500:
          description: Server error

  # --- Reviews ---
  /api/reviews:
    get:
      tags: [Reviews]
      summary: Get all reviews
      responses:
        200:
          description: List of reviews
        500:
          description: Server error
    post:
      tags: [Reviews]
      summary: Create a review (Protected)
      security:
        - oauth2: []
      parameters:
        - in: body
          name: review
          required: true
          schema:
            $ref: "#/definitions/Review"
      responses:
        201:
          description: Review created
        400:
          description: Invalid review data
        401:
          description: Unauthorized
        500:
          description: Server error

  /api/reviews/{id}:
    get:
      tags: [Reviews]
      summary: Get review by ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Review found
        404:
          description: Review not found
        500:
          description: Server error
    put:
      tags: [Reviews]
      summary: Update review (Protected)
      security:
        - oauth2: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: review
          required: true
          schema:
            $ref: "#/definitions/Review"
      responses:
        200:
          description: Review updated
        400:
          description: Invalid data
        401:
          description: Unauthorized
        404:
          description: Review not found
        500:
          description: Server error
    delete:
      tags: [Reviews]
      summary: Delete review (Protected)
      security:
        - oauth2: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        204:
          description: Review deleted
        401:
          description: Unauthorized
        404:
          description: Review not found
        500:
          description: Server error

  # --- Users ---
  /api/users:
    get:
      tags: [Users]
      summary: Get all users (Admin only)
      security:
        - oauth2: []
      responses:
        200:
          description: List of users
        401:
          description: Unauthorized
        500:
          description: Server error
    post:
      tags: [Users]
      summary: Create user manually
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: User created
        400:
          description: Invalid user data
        500:
          description: Server error

  /api/users/{id}:
    get:
      tags: [Users]
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: User found
        404:
          description: User not found
        500:
          description: Server error
    put:
      tags: [Users]
      summary: Update user (Protected)
      security:
        - oauth2: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: User updated
        400:
          description: Invalid data
        401:
          description: Unauthorized
        404:
          description: User not found
        500:
          description: Server error
    delete:
      tags: [Users]
      summary: Delete user (Admin only)
      security:
        - oauth2: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        204:
          description: User deleted
        401:
          description: Unauthorized
        404:
          description: User not found
        500:
          description: Server error

definitions:
  Cake:
    type: object
    properties:
      name:
        type: string
      price:
        type: number
      description:
        type: string
      flavor:
        type: string
      inStock:
        type: boolean

  Order:
    type: object
    properties:
      userId:
        type: string
      cakeId:
        type: string
      quantity:
        type: integer
      totalPrice:
        type: number
      status:
        type: string
        enum: [pending, paid, shipped, delivered]

  Review:
    type: object
    properties:
      cakeId:
        type: string
      userId:
        type: string
      rating:
        type: integer
      comment:
        type: string

  User:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      githubId:
        type: string
      role:
        type: string
        enum: [user, admin]